### ISSUE TITLE
Преобразовать базу данных юзеров

### ISSUE THREAD

**Issue by AlibekBeket** [AlibekBeket/laboratory_68_teamwork#1]
### Для чего это нужно?
Модель является источником информации о наших данных. Она содержит основные поля и поведение данных, которые мы храним. Модель создает таблицу базы данных.
Новая БД позволяет нам различать юзера(соискатель или работодатель наш юзер).
### Как это сделать?
В приложении accounts создать модель "Account", которая наследуется от класса "AbstractUser". После вводить новые поля или изменять дефолтные поля.
Для того чтоб выбрать роль мы создаем класс для выбора роли "RoleChoice"(соискатель или работодатель)
### Дополнительные действия:
Так же нужно зарегистрировать в админке модель "Account".
Так же нужно создать суперюзера для того чтоб мы смогли зайти в админку.
Выполнить миграцию в БД
### Критерии приема
На странице по адресу _/admin/_ мы можем создать юзера с нужными полями.
После миграции появляется таблица  Account
### Планируемое время
4 часа

**Comment by YerbolZhulniyazov** [comment]
Реально потраченное время - 2 часа
