### ISSUE TITLE
Создать модель 'резюме'

### ISSUE THREAD

**Issue by AlibekBeket** [AlibekBeket/laboratory_68_teamwork#3]
### Для чего это нужно?
Модель резюме поможет соискателям увеличить шансы приема на работу, а работодателям найти подходящего сотрудника

### Как это сделать?
Для начала нужно будет создать модель Experience для указания опыта работы соискателя
Поля модели Experience:
* Наименование компании
* Должность
* Обязанности
* Годы работы
* Ключ "соискателя"

Затем надо создать модель Education для указания образования соискателя
Поля модели Education:
* Наименование учебного заведения
* Годы обучения
* Уровень образования
* Выданный документ
* Ключ "соискателя"

Создать модель с классом Resume
Модель Resume включает в себя следующие поля:
* Название резюме
* Ключ "соискателя"
* Желаемая заработная плата
* Желаемый график работы
* Категория вакансии(отношение многие ко многим с базой VacancyCategory)
* Опыт работы(отношение многие ко многим с базой Experience)
* Образование(отношение многие ко многим с базой Education)
* Телефон
* Email
* Telegram
* Ссылка на Facebook
* Ссылка на Linkedin
* Дата создания
* Дата обновления

### Дополнительные действия:
Модели Experience, Education и Resume зарегистрировать в админке

### Критерии приема
На странице по адресу /admin/ мы можем создать уровень образования, опыт работы и само резюме

### Планируемое время
5 часов

**Comment by YerbolZhulniyazov** [comment]
Реально затраченное время - 4 часа
